name: pull_request
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: get the code 
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm install  
            - name: build the code 
              run: npm run build
            - name: test the code
              run: npm run test:report
            - name: publish test result
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: "**/test-results/result.xml"  
                comment_mode: always
